// GeneratorPlugin discovery — OPENCARE_PLAN.md §3.5.
//
// CRITICAL: `import type` ONLY. The CLI executes this file at generation time;
// importing any runtime value here breaks `yarn generate`.
import type { GeneratorPlugin } from '@open-mercato/shared/modules/generators'

// `compliance.packs`: each jurisdiction module ships a `compliance.pack.ts`
// with a default-exported JurisdictionPack. The generator collects them and
// emits a bootstrap-time `registerJurisdictionPacks(...)` call so third-party
// country packs are truly drop-in.
const packsPlugin: GeneratorPlugin = {
  id: 'compliance.packs',
  conventionFile: 'compliance.pack.ts',
  importPrefix: 'COMPLIANCE_PACK',
  configExpr: (importName: string, _moduleId: string) =>
    `(${importName}.default ?? ${importName}.pack)`,
  outputFileName: 'compliance-packs.generated.ts',
  buildOutput: ({ importSection, entriesLiteral }) =>
    `// AUTO-GENERATED by mercato generate registry\n` +
    `import type { JurisdictionPack } from '@/modules/compliance_kit/lib/contract'\n` +
    `${importSection ? `${importSection}\n` : ''}` +
    `export const complianceJurisdictionPacks: JurisdictionPack[] = [\n` +
    `${entriesLiteral ? `  ${entriesLiteral}\n` : ''}]\n`,
  bootstrapRegistration: {
    entriesExportName: 'complianceJurisdictionPacks',
    registrationImports: [
      `import { registerJurisdictionPacks } from '@/modules/compliance_kit/lib/registry'`,
    ],
    buildCall: (name: string) => `registerJurisdictionPacks(${name})`,
  },
}

// `compliance.encryptionMaps`: aggregates each pack module's `encryption.ts`
// `defaultEncryptionMaps` (ModuleEncryptionMap[]) into a single global union,
// so encrypted fields contributed by packs are declared statically and gated
// per-tenant by TENANT_DATA_ENCRYPTION at runtime.
const encryptionMapsPlugin: GeneratorPlugin = {
  id: 'compliance.encryptionMaps',
  // Use a compliance-specific convention filename so this plugin matches ONLY
  // jurisdiction-pack modules. (`encryption.ts` is a generic per-module
  // convention used by every module, so it would over-aggregate the whole app.)
  conventionFile: 'compliance.encryption.ts',
  importPrefix: 'COMPLIANCE_ENCRYPTION',
  configExpr: (importName: string, _moduleId: string) =>
    `...((${importName}.defaultEncryptionMaps ?? []) as unknown[])`,
  outputFileName: 'compliance-encryption-maps.generated.ts',
  buildOutput: ({ importSection, entriesLiteral }) =>
    `// AUTO-GENERATED by mercato generate registry\n` +
    `import type { ModuleEncryptionMap } from '@open-mercato/shared/modules/encryption'\n` +
    `${importSection ? `${importSection}\n` : ''}` +
    `export const complianceEncryptionMaps: ModuleEncryptionMap[] = [\n` +
    `${entriesLiteral ? `  ${entriesLiteral}\n` : ''}]\n`,
}

export const generatorPlugins: GeneratorPlugin[] = [packsPlugin, encryptionMapsPlugin]

export default generatorPlugins
